# Generated by Django 5.0.3 on 2024-03-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('author_slug', models.SlugField(max_length=120)),
                ('dateadded', models.DateField()),
                ('datemodified', models.DateField(auto_now=True)),
                ('tags', models.ManyToManyField(to='quote.tag')),
            ],
        ),
    ]
