# Generated by Django 5.0.3 on 2024-03-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qoute',
            new_name='Quote',
        ),
    ]
