# Generated by Django 5.0.3 on 2024-03-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_rename_qoute_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_id',
            field=models.CharField(db_index=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='datemodified',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
